// S2 TokenComparisonDiagram — three stacked panels showing "what you
// type vs. what the model processes" (4C spec §7).
//
// Token boundaries below are NOT illustrative — they are the actual
// output of the gpt-tokenizer library (cl100k_base) for each input.
// Verified during build via `node -e "..."` (see commit history). When
// the library or vocabulary changes, regenerate by running each input
// through encode()/decode() and updating the TOKENS constants.

import { BottleneckCallout } from '../../components/shared/BottleneckCallout';
import { Overline } from '../../components/shared/Overline';
import { TokenChipList } from './TokenChip';

interface PanelData {
  id: string;
  label: string;
  inputText: string;
  tokens: string[];
  annotation?: string;
}

const PANELS: PanelData[] = [
  {
    id: 'a',
    label: 'Panel A: common English',
    inputText: 'The quarterly revenue report is due Friday.',
    // Verified: gpt-tokenizer (cl100k_base) → 8 tokens.
    tokens: ['The', ' quarterly', ' revenue', ' report', ' is', ' due', ' Friday', '.'],
  },
  {
    id: 'b',
    label: 'Panel B: arithmetic',
    inputText: 'Calculate: 1,279 × 48 = ?',
    // Verified → 11 tokens. Comma and "279" split; leading spaces
    // around operators tokenize separately.
    tokens: ['Calculate', ':', ' ', '1', ',', '279', ' ×', ' ', '48', ' =', ' ?'],
    annotation:
      'The comma splits "1,279" into "1" and "279" — token boundaries follow which digit strings appeared most often in training data, not place value or mathematical structure.',
  },
  {
    id: 'c',
    label: 'Panel C: non-English text',
    inputText: '東京の天気はどうですか',
    // Verified: gpt-tokenizer (cl100k_base) → 11 tokens. The previous
    // 8-token split was the o200k_base output; regenerated when the
    // playground's runtime encoding moved to cl100k_base so the diagram
    // matches what learners see in P5. 東 splits into two byte-level
    // tokens (rendered 東¹ / 東² — neither is a whole character). The
    // English translation lives in the annotation below the chips, not
    // in inputText, so the "What you type" surface stays faithful to
    // what a user would actually paste in.
    tokens: ['東¹', '東²', '京', 'の', '天', '気', 'は', 'ど', 'う', 'です', 'か'],
    annotation:
      'Eleven Japanese characters ("What\'s the weather like in Tokyo?") become eleven tokens — and the first character, 東, is split into two byte-level pieces (marked ¹ and ²), neither of which is a whole character on its own. The same question in English tokenizes into eight.',
  },
];

export function TokenComparisonDiagram(): JSX.Element {
  return (
    <figure
      className="m-0 rounded-lg"
      aria-label="Token comparison diagram: what you type vs. what the model processes"
      style={{
        background: 'rgb(var(--white))',
        border: '1px solid rgb(var(--border))',
        overflow: 'hidden',
      }}
    >
      {/* Space-character legend. Token chips in the panels below use the
          ⎵ glyph to surface space characters that would otherwise be
          invisible — readers unfamiliar with tokenizer output won't
          intuit that whitespace is itself part of a token. The inline
          examples are styled to visually match TokenChip (mono font +
          light surface fill + thin border) so the legend reads as "this
          is what those marks in the panels mean." */}
      <div
        className="font-mono text-caption text-tertiary"
        style={{
          padding: '10px 18px 0',
          letterSpacing: '0.02em',
        }}
      >
        <span style={{ background: 'rgb(var(--surface))', padding: '1px 4px', borderRadius: 3, border: '1px solid rgb(var(--border))' }}>⎵</span>
        {' = space character. Spaces are often bundled into the start of the next token (like '}
        <span style={{ background: 'rgb(var(--surface))', padding: '1px 4px', borderRadius: 3, border: '1px solid rgb(var(--border))' }}>⎵quarterly</span>
        {') rather than standing alone. When they appear as separate tokens, the model processes them as their own unit.'}
      </div>

      {PANELS.map((panel, i) => (
        <ComparisonPanel
          key={panel.id}
          panel={panel}
          isLast={i === PANELS.length - 1}
        />
      ))}

      <div style={{ padding: '14px 18px 18px' }}>
        <BottleneckCallout title="Why this matters">
          <p className="m-0">
            The model never sees words, only statistically derived fragments. Where those
            fragments break determines which tasks produce systematic errors.
          </p>
        </BottleneckCallout>
        <p
          className="m-0 mt-3 font-mono text-caption text-muted"
          style={{ letterSpacing: '0.02em' }}
        >
          Token boundaries shown above are exact, generated by the same{' '}
          <code className="font-mono">gpt-tokenizer</code> library that powers the playground in
          the next section. Different commercial models use different tokenizers, so specifics
          vary in production tools.
        </p>
      </div>
    </figure>
  );
}

function ComparisonPanel({
  panel,
  isLast,
}: {
  panel: PanelData;
  isLast: boolean;
}): JSX.Element {
  return (
    <section
      aria-label={panel.label}
      style={{
        padding: '16px 18px',
        borderBottom: isLast ? 'none' : '1px solid rgb(var(--border-light))',
      }}
    >
      <Overline className="mb-3" style={{ fontSize: 11 }}>
        {panel.label}
      </Overline>

      <div className="mb-1 font-sans text-body-sm font-semibold text-secondary">
        What you type
      </div>
      <div
        className="mb-3 rounded-md font-sans text-body text-ink"
        style={{
          background: 'rgb(var(--surface-warm))',
          border: '1px solid rgb(var(--border-light))',
          padding: '10px 14px',
        }}
      >
        {panel.inputText}
      </div>

      <div className="mb-1 flex items-baseline justify-between gap-3">
        <div className="font-sans text-body-sm font-semibold text-secondary">
          What the model processes
        </div>
        <div className="font-mono text-caption text-tertiary">
          {panel.tokens.length} tokens
        </div>
      </div>
      <div className="-ml-1">
        <TokenChipList
          tokens={panel.tokens}
          ariaLabel={`${panel.tokens.length} token chips for: ${panel.inputText}`}
        />
      </div>

      {panel.annotation && (
        <p className="m-0 mt-3 font-sans text-body-sm italic text-secondary">{panel.annotation}</p>
      )}
    </section>
  );
}
